{{- if .Values.auth.enabled }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-chart.secretName" . }}
  namespace: {{ include "redis-chart.namespace" . }}
  labels:
    {{- include "redis-chart.labels" . | nindent 4 }}
    app: {{ .Values.global.appName }}
    component: auth
    app.kubernetes.io/component: auth
  {{- if .Values.auth.password }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
type: Opaque
data:
  redis-password: {{ include "redis-chart.password" . | b64enc | quote }}
{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-chart.fullname" . }}-monitoring-secret
  namespace: {{ include "redis-chart.namespace" . }}
  labels:
    {{- include "redis-chart.labels" . | nindent 4 }}
    app: {{ .Values.global.appName }}
    component: monitoring
    app.kubernetes.io/component: monitoring
type: Opaque
data:
  monitoring-password: {{ randAlphaNum 24 | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}

